packageExtensions:
  "@jest/core@*":
    peerDependencies:
      ts-node: "*"
    peerDependenciesMeta:
      ts-node:
        optional: true
  debug@*:
    dependencies:
      supports-color: "*"
  jest-cli@*:
    peerDependencies:
      ts-node: "*"
    peerDependenciesMeta:
      "@types/node":
        optional: true
  jest@*:
    peerDependencies:
      ts-node: "*"
    peerDependenciesMeta:
      ts-node:
        optional: true
  vue-eslint-parser@*:
    dependencies:
      "@babel/eslint-parser": "*"
  "@babel/eslint-parser@*": 
    dependencies:
      "@babel/core": "*"



pnpMode: loose

pnpFallbackMode: "all"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
