compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@babel/eslint-parser@*":
    dependencies:
      "@babel/core": "*"
  "@jest/core@*":
    peerDependencies:
      ts-node: "*"
    peerDependenciesMeta:
      ts-node:
        optional: true
  debug@*:
    dependencies:
      supports-color: "*"
  jest-cli@*:
    peerDependencies:
      ts-node: "*"
    peerDependenciesMeta:
      "@types/node":
        optional: true
  jest@*:
    peerDependencies:
      ts-node: "*"
    peerDependenciesMeta:
      ts-node:
        optional: true
  vue-eslint-parser@*:
    dependencies:
      "@babel/eslint-parser": "*"
  vue-jest@*:
    dependencies:
      babel-core: "*"

pnpFallbackMode: all

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.9.2.cjs
